### ISSUE TITLE
Clone Netflix

### ISSUE THREAD

**Issue by sandeep-ahirwar** [sandeep-ahirwar/sudo-clones#1]
as our website is about cloning famous websites. so you can clone any website.
Here you can clone Netflix and put PR

**Comment by pratiksrivastava01** [comment]
@sandeep-ahirwar can we use react or next js for this project? I also want to know if it is a front-end or full-stack project.

**Comment by pratiksrivastava01** [comment]
@sandeep-ahirwar can I work on that

**Comment by sandeep-ahirwar** [comment]
> @sandeep-ahirwar can we use react or next js for this project? I also want to know if it is a front-end or full-stack project.


Yes, you can use react js and next js.

Its a full stack project. If you want to work on just front end or back you can do it your way.

**Comment by sandeep-ahirwar** [comment]
> @sandeep-ahirwar can I work on that

Yes you can.
Assigning it to you @pratiksrivastava01

**Comment by sandeep-ahirwar** [comment]
@pratiksrivastava01  Try to submit it asap!

**Comment by Kpallavi5** [comment]
Hyy I'm interested to work on this issue can you please assign me..

**Comment by sandeep-ahirwar** [comment]
@Kpallavi5 Sorry can't assign this one. You can check other issues also
