### ISSUE TITLE
Clone Facebook

### ISSUE THREAD

**Issue by sandeep-ahirwar** [sandeep-ahirwar/sudo-clones#17]
As our website is about cloning famous websites. so you can clone any website.

Here, Clone Facebook.com

**Comment by sumanparajuli** [comment]
i want to work on this issue.

**Comment by trishitchar** [comment]
@sandeep-ahirwar
I've made 2 Facebook clone using plain CSS and other one with TailwindCSS.
I've pretty good experience on cloning website.
Can you please assign me the work.

**Comment by sandeep-ahirwar** [comment]
> i want to work on this issue.

@sumanparajuli Assigning to you. Get it done ASAP

**Comment by sandeep-ahirwar** [comment]
> @sandeep-ahirwar I've made 2 Facebook clone using plain CSS and other one with TailwindCSS. I've pretty good experience on cloning website. Can you please assign me the work.

@trishitchar You are also assigned to this.
