### ISSUE TITLE
Clone Disney+ Hotstar

### ISSUE THREAD

**Issue by sandeep-ahirwar** [sandeep-ahirwar/sudo-clones#2]
As our website is about cloning famous websites. so you can clone any website.

Here, Clone Disney+ Hotstar.

**Comment by omkarvw** [comment]
Hey can you assign this issue to me. I will learn about it and try to contribute as quickly as possible

**Comment by vivek-dhiman** [comment]
Hey, by clone, do you mean the just landing page of the famous website or the complete clone using backend and all other functionalities?

**Comment by sandeep-ahirwar** [comment]
> 

Firstly landing pages

**Comment by sandeep-ahirwar** [comment]
@vivek-dhiman If you want to work on both frontend + backend you can.
Ping me again If you want to work on it

**Comment by vivek-dhiman** [comment]
@sandeep-ahirwar I want to work on cloning the frontend of the landing page of Disney+ Hotstar.
Please assign this task to me.

**Comment by vivek-dhiman** [comment]
@sandeep-ahirwar I have worked on the clone. And made a PR #24. Please review and suggest any changes or merge it.
