### ISSUE TITLE
Clone Hulu.com

### ISSUE THREAD

**Issue by rtewari056** [sandeep-ahirwar/sudo-clones#22]
Hulu landing page clone

**Comment by yogitha02** [comment]
@rtewari056 please do assign me , i would be glad to clone Hulu Landing page

**Comment by rtewari056** [comment]
> @rtewari056 please do assign me , i would be glad to clone Hulu Landing page

I am not responsible for assigning. Please ask maintainer.

**Comment by sandeep-ahirwar** [comment]
@yogitha02 you are assigned.
