### ISSUE TITLE
Clone Spotify

### ISSUE THREAD

**Issue by sandeep-ahirwar** [sandeep-ahirwar/sudo-clones#3]
As our website is about cloning famous websites. so you can clone any website.

Here, Clone **Spotify**.

**Comment by Adiii1436** [comment]
Hello! I want to work on this issue.

**Comment by sandeep-ahirwar** [comment]
> 

Sure, You can work on it.

**Comment by Adiii1436** [comment]
This issue was assigned to me!!

**Comment by sandeep-ahirwar** [comment]
> This issue was assigned to me!!

Yeah No Issues, You can still do it. Don't worry if you do it well I ll approve your work also.
