### ISSUE TITLE
Clone Stripe Payment Processing Platform

### ISSUE THREAD

**Issue by rtewari056** [sandeep-ahirwar/sudo-clones#35]
I want to build a clone of [Stripe Payment Processing Platform](https://stripe.com).

### About Stripe
Stripe is a suite of APIs powering online payment processing and commerce solutions for internet businesses of all sizes. Accept payments and scale faster.

### Screenshot
![192692088-24578ec3-e90c-4724-beaa-0bdba72c8c68](https://user-images.githubusercontent.com/75976169/193751699-22445c03-22d9-458f-8a0a-64fdd855bcda.png)

**Comment by sandeep-ahirwar** [comment]
@rtewari056 go for it
