### ISSUE TITLE
Clone Zerodha.com

### ISSUE THREAD

**Issue by sohan2503001** [sandeep-ahirwar/sudo-clones#38]
I want to build clone of zerodha website it is stock trading company
link : https://zerodha.com/

![Screenshot (468)](https://user-images.githubusercontent.com/69068073/194242978-d492dd2b-f833-4f61-93b6-764089be2006.png)

**Comment by sohan2503001** [comment]
@sandeep-ahirwar can you assign me this issue

**Comment by sandeep-ahirwar** [comment]
@sohan2503001 assigned

**Comment by AaryanSingh0017** [comment]
Plz assign me

**Comment by sandeep-ahirwar** [comment]
@AaryanSingh0017 assigned
