### ISSUE TITLE
Clone Fila.com

### ISSUE THREAD

**Issue by sohan2503001** [sandeep-ahirwar/sudo-clones#59]
I want to make clone of Fila Website
link : https://www.fila.com/

![FILA-com-Official-Site-Sportswear-Sneakers-Tennis-Apparel](https://user-images.githubusercontent.com/69068073/194911549-e44a9d4e-9895-46a8-9474-00443919b5c3.png)

**Comment by sohan2503001** [comment]
@sandeep-ahirwar can u assign me this issue

**Comment by sandeep-ahirwar** [comment]
@sohan2503001 assigned
