### ISSUE TITLE
Clone Github Profile Page

### ISSUE THREAD

**Issue by sandeep-ahirwar** [sandeep-ahirwar/sudo-clones#6]
This will be an interesting work for front end developers.

![image](https://user-images.githubusercontent.com/78246750/193397431-4094480a-5f5a-43a6-a452-8e16745cc99a.png)

**Comment by AsmaKacem1** [comment]
Hey @sandeep-ahirwar ,can I work on this

**Comment by sandeep-ahirwar** [comment]
@AsmaKacem1 You can work on this. Assigning this issue to you
