### ISSUE TITLE
Clone Apple.com

### ISSUE THREAD

**Issue by sandeep-ahirwar** [sandeep-ahirwar/sudo-clones#7]
This one is tough.

As our website is about cloning famous websites. so you can clone any website.

Here, Clone Apple.com

**Comment by AsmaKacem1** [comment]
Hey @sandeep-ahirwar ,can I work on this

**Comment by sandeep-ahirwar** [comment]
@AsmaKacem1 Assigned to you.

**Comment by sandeep-ahirwar** [comment]
@AsmaKacem1  any work update?

**Comment by sohan2503001** [comment]
Hey @sandeep-ahirwar can you assign me this issue

**Comment by sandeep-ahirwar** [comment]
> Hey @sandeep-ahirwar can you assign me this issue

Sure @sohan2503001
