### ISSUE TITLE
Clone SpeedTest.net 

### ISSUE THREAD

**Issue by sandeep-ahirwar** [sandeep-ahirwar/sudo-clones#8]
As our website is about cloning famous websites. so you can clone any website.

Here, Clone SpeedTest.net

Improve its UI
This is a full stack clone

**Comment by atom540** [comment]
can I work on this topic? so, please assign this project to me.

**Comment by sandeep-ahirwar** [comment]
> can I work on this topic? so, please assign this project to me.

Sure. Assigned to you
